### ISSUE TITLE
Work Cells Button

### ISSUE THREAD

**Issue by tea1677** [kc9eye/UData#47] opened 2019-01-22 14:38 UTC
When pressing the work cells button I get an error message. "No Cells Found For This Product"

**Comment by kc9eye** [comment] 2019-01-22 15:42
Which product?

Paul W. Lane
KC9EYE
Chicago Assembly Division
________________________________

**Comment by kc9eye** [comment] 2019-01-22 16:36
![number47_unconfirmed](https://user-images.githubusercontent.com/7613798/51550185-7f54b780-1e31-11e9-99f8-0c44272b478c.png)
I can not confirm this without more info. Seems to be working on my end.

**Comment by tea1677** [comment] 2019-01-23 01:42
It was RV

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by kc9eye** [comment] 2019-01-23 14:11
I can't find anything wrong with it at this time. It is working on my machine, as shown by the screenshot above. Clicking on the RV Final release does produce this issue, as there are currently no cells assigned to that product. I'm closing this issue as unconfirmed.

**Closed by kc9eye** 2019-01-23 14:11 UTC
Labels: bug
